### ISSUE TITLE
Integration steps for golang

### ISSUE THREAD

**Issue by dhairya-chai** [grab/grabpay-merchant-sdk#1]
The doc tells how to use the SDK in a standalone environment but doesn't tells on how to integrate with existing backend.

**Comment by 0123456hahaha0123456** [comment]
Hi @dhairya-chai, please refer to code in https://github.com/grab/grabpay-merchant-sdk/blob/main/Go/test/main/main.go, you only need add the same code to existing backend for using API

**Comment by dhairya-chai** [comment]
Got it thanks 👍
